In [20]:
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt # for making figures
%matplotlib inline

In [ ]:
#Reading the words
words = open("names.txt", "r").read().splitlines()
#words[:10]

In [3]:
len(words)

32033

In [21]:
#Mapping characters to integers

chars = sorted(list(set("".join(words))))
stoi = {s:i+1 for i,s in enumerate(chars)}
stoi["."] = 0
itos = {i:s for s,i in stoi.items()}
print(itos)


{1: 'a', 2: 'b', 3: 'c', 4: 'd', 5: 'e', 6: 'f', 7: 'g', 8: 'h', 9: 'i', 10: 'j', 11: 'k', 12: 'l', 13: 'm', 14: 'n', 15: 'o', 16: 'p', 17: 'q', 18: 'r', 19: 's', 20: 't', 21: 'u', 22: 'v', 23: 'w', 24: 'x', 25: 'y', 26: 'z', 0: '.'}


In [22]:
#Building the Dataset
block_size = 3
X, y = [], []

for w in words[:3]:
    context = [0] * block_size
    for ch in w + '.':
        ix = stoi[ch]
        X.append(context)
        y.append(ix)
        print("".join(itos[i] for i in context), '------>', itos[ix])
        context = context[1:] + [ix]

X = torch.tensor(X)
y = torch.tensor(y)

... ------> e
..e ------> m
.em ------> m
emm ------> a
mma ------> .
... ------> o
..o ------> l
.ol ------> i
oli ------> v
liv ------> i
ivi ------> a
via ------> .
... ------> a
..a ------> v
.av ------> a
ava ------> .


In [ ]:
#Explanation for how context is just a series of numbers that acts as input
#And y is the next character in the form of a number.

block_size = 3
context = [0] * block_size
print(context)

[0, 0, 0]


In [23]:
X.shape, X.dtype, y.shape, y.dtype

(torch.Size([16, 3]), torch.int64, torch.Size([16]), torch.int64)

In [27]:
#Creating a look up table. 

C = torch.randn(27,2)

In [29]:
C[X].shape

torch.Size([16, 3, 2])

In [34]:
C[X][13,2]

tensor([-0.4796,  1.2048])

In [ ]:
C[1]

#Both are same  

tensor([-0.4796,  1.2048])

In [36]:
emb = C[X]
emb.shape

torch.Size([16, 3, 2])

In [39]:
#Creating weights and biases. We wanna keep 100 neuros so 100 and 6 is 3*2 of emb

w1 = torch.randn((6, 100))
b1 = torch.randn(100)

In [43]:
#Calculating hidden state. embbeddings * weights + biases
# -1 is for torch to calculate the right number there
h = torch.tanh(emb.view(-1,6) @ w1 + b1)

In [44]:
h

tensor([[ 0.9960,  0.9999,  1.0000,  ..., -0.9678, -1.0000, -0.9998],
        [ 0.9970,  0.9987,  0.9999,  ...,  0.4012, -0.9999, -0.9862],
        [ 0.8735,  0.9993,  1.0000,  ..., -0.3644,  0.4792,  0.9973],
        ...,
        [ 0.9960,  0.9983,  0.9998,  ...,  0.0586, -1.0000, -0.9972],
        [ 0.9536,  0.9818,  1.0000,  ...,  0.2943, -0.8802,  0.9077],
        [-0.8129, -0.9885, -0.4227,  ...,  0.9694, -0.9752,  0.9953]])